version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sap-clone-postgres
    environment:
      POSTGRES_DB: sapclone
      POSTGRES_USER: sapuser
      POSTGRES_PASSWORD: sappassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sapuser -d sapclone"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local 